version: '3.8'

services:
  db:
    container_name: db
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: docker_symfony
      POSTGRES_USER: root
      PGDATA: /var/lib/pg_data
    ports:
      - 15432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - symfony

  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ../app:/var/www/symfony_docker
    depends_on:
      - db
    networks:
      - symfony

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../app:/var/www/symfony_docker
    ports:
      - 8001:80
    networks:
      - symfony
networks:
  symfony:
